language: python

python:
  - "3.6"
  - "3.7"

branches:
  only:
  - master

services:
  - mysql

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements-prod.txt

script:
  - pytest

cache:
  - pip