# Generated by Django 3.0.6 on 2020-05-24 10:48

from django.db import migrations, models
import farmers.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/user.svg', upload_to=farmers.models.profile_pic_filename, verbose_name='Profile Picture'),
        ),
    ]
