# Generated by Django 3.0.6 on 2020-05-28 15:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_auto_20200524_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='street',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='website',
            field=models.CharField(blank=True, default='http://fagrimacs.com', max_length=254, validators=[django.core.validators.URLValidator()]),
        ),
    ]
